### ISSUE TITLE
Structure of config.json file ?

### ISSUE THREAD

**Issue by NGorsel** [yzwetsloot/BolBot#8]
Hello! I love your script and I would like to run it a few times to see how it performs. However, an error occurred when I tried. If I run the script I get the following error.
```
(venv) MacBook-Pro-3:src USER$ python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from operation import insert, update, notify
  File "/Users/USER/Projects/BolBot/src/operation.py", line 4, in <module>
    from notification import price_notification
  File "/Users/USER/Projects/BolBot/src/notification.py", line 13, in <module>
    data = json.load(config)
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/USER/.pyenv/versions/3.8.0/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The structure of my folder looks as follows:
- Config
     - config.json
     - log.yaml
- Resources
     - template.html
     - urls.txt
- src
     - database.py
     - main.py
     - notification.py
     - operation.py
     - proxy.py

The error is definitely caused by the fact that I just added an empty config.json and log.yaml file in the config folder. However, I can't find any documentation on how the config.json file should look like? Based on your readme.txt file it should contain atleast a few settings? 

> * Set BOL_ONLY flag to true in the config.json file so that only products sold by Bol.com will be checked and stored.

However, I cant seem to find which content the config.json file should contain. Any help is highly appreciated so I can run this script a couple of times to see how it performs! Thanks in advance.

**Comment by yzwetsloot** [comment]
Hi there, thanks for the kind words!

Below I've included a template for the `config.json`-file.
```json
{
  "min_price" : 0,
  "treshold" : 0,
  "min_proxies" : 0,
  "batch_size" : 200,
  "thread_count" : 0,
  "process_count" : 0,
  "timeout" : 0,
  "start_pattern" : "number-of-articles",
  "end_pattern" : "offcanvas-container",
  "bol_only" : false,
  "base_url" : "https://www.bol.com",
  "connect_timeout" : 0.0,
  "read_timeout" : 0.0,
  "db_config" : {
    "user": "",
    "password": "",
    "host": "",
    "port": "",
    "database": ""
  },
  "email_config" : {
    "password": "",
    "sender": "",
    "receiver": "",
    "port": 0
  }
}
```

You can look up most of their usages within the program to figure out their exact purpose.
The `treshold` refers to the relative price drop that has to occur for an e-mail to be send (f.e. 0.45 corresponds to a 55% price drop). 
The `thread-count` and `process-count` refer to the max. number of threads (e.g. 50) and max. number of processes respectively.
The `min-proxies` refers to the number of proxies for a cycle to start, if not enough proxies are found it will timeout and start again (this is what the `timeout` is for).
The `connect-timeout` and `read-timeout` determine when a request times out. 
The keys for which I have provided a value I'd keep as is (f.e. the `start-pattern` and `end-pattern`).

For setting up the `e-mail_config` I recommend the following link:
https://realpython.com/python-send-email/
It explains how to set-up sending e-mails with a Gmail developer account.

**Comment by yzwetsloot** [comment]
Template .yaml-file for logging configuration.
```yaml
version: 1
formatters:
  standard:
    format: "[your-format-here]"
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: "../app.log"
loggers:
  logger:
    level: INFO
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [file]
```
For more information on this, see:
https://realpython.com/python-logging/
